[general]
import = [
    "~/.alacritty-themes/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
blur = true
opacity = 0.99

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
